name: web3_wallet
description: 多链Web3钱包，支持BTC、ETH、BSC等主流链的创建、导入、收款、转账等
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.0.0
  bdk_flutter: ^0.31.3
  web3dart: ^2.7.0
  bip39: ^1.0.6
  bip32: ^2.0.0
  qr_flutter: ^4.0.0
  http: ^1.2.0
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  hive_generator: ^2.0.1

flutter:
  generate: true